# JustAFK Configuration
tagmessages: true

# AFK-related options
autokick: true
movementcheckfreq: 30 #seconds
kicktime: 300 #seconds
kickreason: '&cYou were inactive for too long!'
kickwhileinvehicle: false
